Oddam-w-dobre-r-ce/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

]

Oddam-w-dobre-r-ce/mysite/polls/urls.py
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
#    path('', views.entry_welcome, name='welcome'),
#    path('products/', views.entry_welcome, name='products'),
    path('', views.Index.as_view(), name='home'),
#    path('admin/', admin.site.urls),
    path('landing_page/', views.Landing_Page.as_view(), name='landing_page'),
    path('form/', views.AddDonation, name='form'),
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('index/', views.Index.as_view(), name='index'),
    path('activate/<uidb64>/<token>', views.ActivateAccount.as_view(), name='activate'),
    path('accounts/', include('django.contrib.auth.urls')),

]

Oddam-w-dobre-r-ce/mysite/polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from .managers import CustomUserManager
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = ('Kategorie')

class Institution(models.Model):

    class InstitutionType(models.TextChoices):
        FOUNDATION = 'FUND', 'Fundacja',
        NON_GOV = 'NGOV', 'Organizacja pozarządowa',
        CHARITY = 'CHAR', 'Zbiórka lokalna',

    institution_type = models.CharField(max_length=4,
                                        choices=InstitutionType.choices,
                                        default=InstitutionType.FOUNDATION)

    name = models.CharField(max_length=128)
    description = models.TextField()

    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = ('Instytucje')


class Donation(models.Model):
    quantity = models.DecimalField(max_digits=6, decimal_places=2)
    categories = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    institution = models.ForeignKey(to=Institution, on_delete=models.CASCADE)
    address = models.TextField()
    address_home_nr = models.DecimalField(max_digits=6, decimal_places=3)
    phone_number = models.DecimalField(max_digits=9,  decimal_places=0)
    city = models.TextField()
    zip_code = models.DecimalField(max_digits=5, decimal_places=0)
    pick_up_date = models.DateField()
    pick_up_time = models.IntegerField()
    pick_up_comment = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.institution.name

    class Meta:
        ordering = ('pick_up_date', 'pick_up_time')
        verbose_name_plural = ('Donacje')

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(unique=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

Oddam-w-dobre-r-ce/mysite/polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import Category
from .models import Institution
from .models import Donation
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model, login
import ipdb
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.db.models import ExpressionWrapper, F, DateTimeField
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from .forms import (
    AddDonationFormStepOne,
    AddDonationFormStepTwo,
    AddDonationFormStepThree,
    AddDonationStepFour,
    AddDonationFormStepFive,
    LoginForm,
    UserEditForm,
    UserPasswordChangeForm,
    UserCreationForm,
    SignUpForm)

from django.views.generic import (
    CreateView,
    DetailView,
    UpdateView,
    FormView,
    TemplateView
)
from .tokens import email_verification_token
from formtools.wizard.views import SessionWizardView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import ipdb
from django.conf import settings



class Index(View):
        def get(self, request, *args, **kwargs):
            donations = Donation.objects.all()
            foundations = Institution.objects.filter(institution_type='FUND')
            charity = Institution.objects.filter(institution_type='CHAR')
            quantity = sum([donation.quantity for donation in donations])
            institutions = len(set([donation.institution_id for donation in
                                    donations]))
#TO DO: zmienic pag na 5
            found_paginator = Paginator(foundations, 3)
            page = request.GET.get('page1')
            try:
                paged_foundations = found_paginator.page(page)
            except PageNotAnInteger:
                paged_foundations = found_paginator.page(1)
            except EmptyPage:
                paged_foundations = found_paginator.page(found_paginator.num_pages)

            ngos = Institution.objects.filter(institution_type='NGOV')
            ngos_paginator = Paginator(ngos, 3)

 #           found_paginator = Paginator(foundations, 3)
            page = request.GET.get('page2')
            try:
                paged_ngos = ngos_paginator.page(page)
            except PageNotAnInteger:
                paged_ngos = ngos_paginator.page(1)
            except EmptyPage:
                paged_ngos = ngos_paginator.page(ngos_paginator.num_pages)



            charity = Institution.objects.filter(institution_type='CHAR')
            charity_paginator = Paginator(charity, 2)

 #           found_paginator = Paginator(foundations, 3)
            page = request.GET.get('page3')
            try:
                paged_charity = charity_paginator.page(page)
            except PageNotAnInteger:
                paged_charity = charity_paginator.page(1)
            except EmptyPage:
                paged_charity = charity_paginator.page(charity_paginator.num_pages)

#            page_number = request.GET.get('foundations')
 #           foundations = found_paginator.get_page(page_number)
  #          page_number = request.GET.get('page2')
   #         ngos = ngos_paginator.get_page(page_number)
    #        page_number = request.GET.get('page3')
     #       charities = charity_paginator.get_page(page_number)


            context = {
                'quantity': quantity,
                'institutions': institutions,
                'foundations': paged_foundations,
                'ngos': paged_ngos,
                'charity': paged_charity
                #            'queryset': queryset
                #            'user_id': request.user.id
            }
            return render(request, 'index.html', context)


class Landing_Page(View):
    def get(self, request, *args, **kwargs):
        donations = Donation.objects.all()
        foundations = Institution.objects.filter(institution_type='FUND')
        charity = Institution.objects.filter(institution_type='CHAR')
        quantity = sum([donation.quantity for donation in donations])
        institutions = len(set([donation.institution_id for donation in
                                donations]))

        found_paginator = Paginator(foundations, 5)
        ngos = Institution.objects.filter(institution_type='NGOV')
        ngos_paginator = Paginator(ngos, 5)
        charity = Institution.objects.filter(institution_type='CHAR')
        charity_paginator = Paginator(charity, 5)

        page_number = request.GET.get('foundations')
        foundations = found_paginator.get_page(page_number)
        page_number = request.GET.get('page2')
        ngos = ngos_paginator.get_page(page_number)
        page_number = request.GET.get('page3')
        charities = charity_paginator.get_page(page_number)

        context = {
            'quantity': quantity,
            'institutions': institutions,
            'foundations': foundations,
            'ngos': ngos,
            'charitiy': charity

    }
        return render(request, 'index.html', context)


def AddDonation(request):
    queryset = Category.objects.all()

    context = {
        'queryset': queryset

    }
    return TemplateResponse(request, 'form.html', context)


class Login(LoginView):

    form_class = LoginForm
    template_name = "login.html"


class Register(SuccessMessageMixin, CreateView):
    model = get_user_model()
    form_class = SignUpForm
    template_name = "register.html"
    success_url = reverse_lazy('login')

    def form_valid(self, form):

        user = form.save(commit=False)
        to_email = form.cleaned_data.get('email')
        user.username = to_email
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        mail_subject = 'Proszę o aktywację konta na charity - donation.'
        message = render_to_string('to_activate_account.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': email_verification_token.make_token(user),
        })

        email = EmailMessage(
                mail_subject,message, to=[to_email]

        )
        email.send()
        return super(RegisterView, self).form_valid(form)

    def get_success_message(self, cleaned_data):
        return "Konto pomyślnie zarezerwowane! Wymagana aktywacja przez adres email."




class AddDonationView(SessionWizardView):
    form_list = (
        AddDonationFormStepOne,
        AddDonationFormStepTwo,
        AddDonationFormStepThree,
        AddDonationStepFour,
        AddDonationFormStepFive

    )
    def get_context_data(self, form, **kwargs):
        context = super(AddDonationView, self).get_context_data(form, **kwargs)
        context['categories'] = Category.objects.all()
        context['institutions'] = Institution.objects.all()
        return context

    def get(self, request, *args, **kwargs):
        try:
            return self.render(self.get_form())
        except KeyError:
            return super().get(request, *args, **kwargs)

    def get_form_initial(self, step):
        if step == '2':
            step0data = self.get_cleaned_data_for_step('0')
            if step0data:
                categories = step0data.get('categories', '')
                return self.initial_dict.get(step, {'categories': categories})
        return self.initial_dict.get(step, {})

    def done(self, form_list, **kwargs):
        form_data = [form.cleaned_data for form in form_list]
        categories = form_data[0]['categories']
        donation = Donation.objects.create(
            quantity = form_data[1]['quantity'],
            institution = form_data[2]['institution'],
            address = form_data.cleaned_data['address'],
            city = form_data.cleaned_data['city'],
            zip_code = form_data.cleaned_data['zip_code'],
            phone_number = form_data.cleaned_data['phone_number'],
            pick_up_date = form_data.cleaned_data['pick_up_date'],
            pick_up_time = form_data.cleaned_data['pick_up_time'],
            pick_up_comment = form_data.cleaned_data['pick_up_comment'],
            user=self.request.user

        )
        donation.categories.set(categories)
        return render(self.request,'form-confirmation.html', {'form_data': [
            form.cleaned_data for form in form_list]})

#TO DO:do usunięcia
#class Activate(View):
#    template_name = 'login.html'

#    def get(self, request, uidb64, token):
#        try:
#            uid = force_text(urlsafe_base64_decode(uidb64))
#            user = User.objects.get(pk=uid)

#        except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
#            user = None
#        if user is not None and email_verification_token.check_token(user, token):
#            user.is_active = True
#            user.save()
#            messages.add_message(request, messages.INFO, 'Konto aktywne. Możesz się teraz zalogować.')
#            return render(request, self.template_name)
#        else:
#            messages.add_message(request, messages.WARNING, 'Link aktywacyjny wygasł.')
#            return render(request, self.template_name)

class ProfileView(UserPassesTestMixin, LoginRequiredMixin, DetailView):

#    model = CustomUser
#    template_name = 'profile.html'
#    pk_url_kwarg = 'pk'

    def test_func(self):

Oddam-w-dobre-r-ce/mysite/polls/templates/base.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <header class="header--main-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          <li><a href="{% url 'login'%}#section-1" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href="{% url 'signup'%}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>

        <ul>
          <li><a href="{% url 'index'%}" class="btn btn--without-border active">Start</a></li>
          <li><a href="{% url 'index'%}#section-4">O co chodzi?</a></li>
          <li><a href="{% url 'index'%}#section-5" class="btn btn--without-border">O nas</a></li>
          <li><a href="{% url 'index'%}#section-6" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="{% url 'form'%}#section-3" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="{% url 'index'%}#section-7" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      </header>
        {% block content %}

        {% endblock %}
  </body>
</html>

Oddam-w-dobre-r-ce/mysite/polls/templates/change_password.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Zmień hasło
{% endblock %}

{% block content %}
    <div>
        {% if messages %}
            {% for message in messages %}
                <h2>{{ message }}</h2>
            {% endfor %}
        {% endif %}
    </div>
    <section class="login-page">
      <h2>Zmień hasło</h2>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
      <form action="" method="POST">
          {% csrf_token %}
        <div class="form-group">
          <input type="password" name="old_password" placeholder="Stare hasło">
        </div>
        <div class="form-group">
          <input type="password" name="new_password1" placeholder="Nowe hasło">
        </div>
        <div class="form-group">
          <input type="password" name="new_password2"
                 placeholder="Powtórz nowe hasło">
        </div>

        <div class="form-group form-group--buttons">
          <button class="btn" type="submit">Zapisz hasło</button>
        </div>
      </form>
    </section>
{% endblock %}

Oddam-w-dobre-r-ce/mysite/polls/templates/donation_detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    Szczegóły zbiórki
{% endblock %}

{% block header %}
    <div>
        {% if messages %}
            {% for message in messages %}
                <h2>{{ message }}</h2>
            {% endfor %}
        {% endif %}
    </div>
    <header class="header--main-page">
        {% include "nav.html" %}
        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1> Dary dla
                    {{ object.institution.get_institution_type_display }}
                    {{ object.institution }}
                </h1>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em>Ilość przekazanych worków: {{ object.quantity }}</em>
                <h3>Kategorie: {% for category in object.categories.values %}
                    {% if forloop.counter < object.categories.values|length %}
                        {{ category.name }},
                    {% else %}
                        {{ category.name }}.
                    {% endif %}
                    {% endfor %}</h3>
                <p>Termin odbioru: {{ object.pick_up_date }},
                    {{ object.pick_up_time }}. <br>
                    Uwagi do odbioru: {{ object.pick_up_comment }}
                </p>

            </div>
        </div>
    </section>
{% endblock %}

Oddam-w-dobre-r-ce/mysite/polls/templates/donations.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    Twoje zbiórki
{% endblock %}

{% block header %}
    <header class="header--main-page">
        {% include "nav.html" %}
        <div class="slogan container container--90">
            <div class="slogan--item">
                <h1>
                    {% if picked_up|length == 0 %}
                        Zacznij pomagać!
                    {% else %}
                        Twoje wsparcie trafiło już<br>
                        do {{ picked_up|length }} organizacji.
                    {% endif %}
                </h1>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <section id="stats" class="stats">
        <div class="container container--85">
            <div class="stats--item">
                <em>Odebrane</em>
                {% for donation in picked_up %}
                <h3>{{ donation.institution }}</h3>
                <p>Odebrano: {{ donation.my_dt }}.
                    <a href="{% url 'donation-detail' donation.pk %}">Szczegóły
                    &raquo;</a></p>
                {% endfor %}
            </div>
            <div class="stats--item" style="width: 300px"></div>
            <div class="stats--item">
                <em>Do odbioru</em>
                {% for donation in ordered %}
                <h3>{{ donation.institution }}</h3>
                <p>Termin odbioru: {{ donation.my_dt }}.
                    <a href={% url 'donation-detail' donation.pk %}>Szczegóły
                    &raquo;</a></p>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

Oddam-w-dobre-r-ce/mysite/polls/templates/edit_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Profil użytkownika
{% endblock %}

{% block content %}
    <section class="login-page">
        <h1>Edytuj dane</h1>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="stats--item">
                <div class="form-group">
                    <input type="text" name="first_name" placeholder="Imię"
                           value="{{ object.first_name }}">
                </div>
                <div class="form-group">
                    <input type="text" name="last_name" placeholder="Nazwisko"
                           value="{{ object.last_name }}">
                </div>
                <div class="form-group">
                    <input type="email" name="email" placeholder="Email"
                           value="{{ object.email }}">
                </div>
                <div class="form-group">
                    <input type="password" name="confirm_password"
                           placeholder="Wprowadź hasło">
                </div>

                <div class="form-group form-group--buttons">
                    <button class="btn" type="submit">Zmień dane</button>
                </div>
            </div>
        </form>
    </section>

{% endblock %}

Oddam-w-dobre-r-ce/mysite/polls/templates/form-confirmation.html
{% extends 'base.html' %}

{% block content %}
      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="js/app.js"></script>
  </body>
</html>

{% endblock %}

Oddam-w-dobre-r-ce/mysite/polls/templates/index.html
{% extends 'base.html' %}

{% block content %}
      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    </header>

    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>10</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>5</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>
          <a name="section-4"> </a>
    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'signup'%}" class="btn btn--large">Załóż konto</a>
    </section>
                <a name="section-5"> </a>
    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="images/signature.svg" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="images/about-us.jpg" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
       <a name="section-6"> </a>
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->

      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

        {% if foundations %}
        <ul class="help--slides-items">
            {% for foundation in foundations %}
          <li>
            <div class="col">
              <div id="foundation_title" class="item_value">{{ foundation.name }}</div>
              <div id="foundation_subtitle" class="item_value">{{ foundation.description }}</div>
            </div>

            <div id="foundation_text" class="item_value">{{ foundation.text }}</div>
          </li>
            {% endfor %}
        </ul>
        <!-- Pagination -->
        <span class="step-links pagination">
            {% if foundations.has_previous %}
                <a href="?page1={{ foundations.previous_page_number }}"> previous </a>
            {% endif %}
            <span class="current">
                Page {{ foundations.number }} of {{ foundations.paginator.num_pages }}
            </span>
            {% if foundations.has_next %}
                <a href="?page1={{ foundations.next_page_number }}"> next </a>
            {% endif %}
        </span>
        {% endif %}
       <!-- -->
      </div>
         <hr />
      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          W naszej bazie znajdziesz listę zweryfikowanych Organizacji
                pozarządowych, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.
        </p>
          {% if ngos %}
        <ul class="help--slides-items">
             {% for ngo in ngos %}
        <li>
            <div class="col">
              <div id="foundation_title" class="item_value">{{ngo.name}}</div>
              <div id="foundation_subtitle" class="item_value">{{ngo.description}}</div>
            </div>

            <div id="foundation_text" class="item_value">{{ngo.text}}</div>
          </li>
            {% endfor %}
        </ul>

        <!-- Pagination -->
       <span class="step-links pagination">
            {% if ngos.has_previous %}
                <a href="?page2={{ ngos.previous_page_number }}"> previous </a>
            {% endif %}
            <span class="current">
                Page {{ ngos.number }} of {{ ngos.paginator.num_pages }}
            </span>
            {% if ngos.has_next %}
                <a href="?page2={{ ngos.next_page_number }}"> next </a>
            {% endif %}
        </span>
        {% endif %}
        -->
      </div>

          <hr />
      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p> W naszej bazie znajdziesz listę zweryfikowanych lokalnych
                zbiórek. Możesz sprawdzić jaki jest cel zbiórki i
                jakie są najpilniejsze potrzeby.</p>
           {% if charity %}
        <ul class="help--slides-items">
            {% for char in charity %}
        <li>
            <div class="col">
              <div id="foundation_title" class="item_value">{{char.name}}</div>
              <div id="foundation_subtitle" class="item_value">{{char.description}}</div>
            </div>

            <div id="foundation_text" class="item_value">{{char.text}}</div>
          </li>
            {% endfor %}

        </ul>

        <!-- Pagination -->
        <span class="step-links pagination">
            {% if charity.has_previous %}
                <a href="?page3={{ charity.previous_page_number }}"> previous </a>
            {% endif %}
            <span class="current">
                Page {{ charity.number }} of {{ charity.paginator.num_pages }}
            </span>
            {% if charity.has_next %}
                <a href="?page3={{ charity.next_page_number }}"> next </a>
            {% endif %}
        </span>
        {% endif %}
        -->
      </div>

    </section>
                <a name="section-7"> </a>
    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
          <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

          <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src="images/icon-facebook.svg"/></a>
          <a href="#" class="btn btn--small"><img src="images/icon-instagram.svg"/></a>
        </div>
      </div>
    </footer>

    <script src="js/app.js"></script>
  </body>
</html>

{% endblock %}

Oddam-w-dobre-r-ce/mysite/polls/templates/password_reset_form.html
{% extends 'base.html' %}

{% block title %} Zmiana hasła {% endblock %}

{% block content %}

<section class="login-page">
    <h2>Zapomniałeś/aś hasła? Podaj adres email na który wyślemy instrukcje.</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <p>{{ form.email }}</p>
        </div>
        <div class="form-group form-group--buttons">
            <button name="submit" class="btn">Wyślij prośbę</button>
        </div>
    </form>
</section>
{% endblock %}